import type { Expression } from './geometry'

const calibrated: number[][] = [
  [7.3, 27.8, -16.1, 24.2, 27.6, 38.9, 40.7, 54.3, -20.5, 0, 0],
  [-35.6, 0.7, -8.5, 29.4, 27.3, 49.5, 49.8, 57.7, -42, 0, 0],
  [-36.2, 13.1, 15.5, 44.3, 51.3, 74.2, 76, 68.7, -40.7, 0, 0],
  [15.6, -16.5, -11.3, 54, 51, 49.6, 48.5, 70.9, 30.1, 0, 0],
  [3.4, 13, 8.9, 42.6, 44, 17.3, 16, 57.9, 4.9, 0, 0],
  [-17.7, -1.4, -8.8, 29.5, 19.2, 51.6, 41.9, 56.3, 0, 0, 90],
  [14.8, 14.5, 5.5, 22.9, 22.2, 32.4, 33.4, 50.9, 39.2, 0, 0],
  [25.7, 16.5, -13.5, 48.5, 48.3, 33.5, 33, 53.3, 41.3, 61.3, -80],
  [-22.8, -15.9, 6.2, 44.5, 43.9, 32.3, 24.6, 54.9, -42, -60.9, 69.2],
  [-11.6, 8.3, -12.7, 42.5, 22.1, 41.8, 22.2, 61.7, 12.3, 0, 0],
  [20.3, 7, 8.7, 30.2, 28.1, 48.8, 49.2, 56.8, 39.9, 0, 0],
  [17.5, -15.2, -8.7, 51, 49.2, 75.3, 73.4, 70.2, 41.6, 0, 0],
  [-10.4, 15.2, 11.8, 50.6, 51.6, 50, 50.7, 69.5, 16.7, 0, 0],
  [-6, -7.7, -9.4, 43.6, 42.8, 15.5, 18.1, 57.9, 3.5, 0, 0],
  [0.2, -3.1, 9, 29.6, 16.8, 51.5, 41.3, 56.4, -7.8, 0, 90],
  [-16.2, 38.4, 2.4, 23.7, 26.2, 32.7, 34.6, 53.9, -41.1, 0, 0],
  [3.5, -16.1, 15.8, 51, 48.5, 34.9, 33, 55.1, 41.9, 80, -62.2],
  [-17.3, 11.2, -9.1, 24.2, 44.5, 44.5, 32.2, 55, -36.5, 18.5, 67.9],
  [-0.7, 3.6, 12.2, 42.1, 22.2, 41.7, 22.1, 60.4, -9.1, 0, 0],
  [-25.3, -12.4, -13.3, 30.5, 26.8, 49.9, 48.8, 56.2, -35.8, 0, 0],
  [-41.1, 20.2, 18.8, 44.6, 53, 74.9, 77.8, 70.8, -40.6, 0, 0],
  [-14.6, -12.5, -16.1, 51.4, 50.5, 50.1, 49.4, 69, -20, 0, 0],
  [10, 2.7, 8.8, 42.9, 43.3, 16.4, 17.8, 57.9, 2.7, 0, 0],
  [-17.8, 10, -6.3, 28.8, 17.3, 51.4, 42.7, 56.6, -9.8, 0, 90],
  [-29.6, 7.5, 10.1, 21.5, 23.2, 32, 33.5, 51.2, -37.4, 0, 0],
]

const calibratedExpressions: Expression[] = calibrated.map(
  (
    [
      headX,
      headY,
      headZ,
      widthLeft,
      widthRight,
      heightLeft,
      heightRight,
      spacing,
      latitude,
      leftAngle,
      rightAngle,
    ],
    index
  ) => ({
    id: `expression-${String(index).padStart(2, '0')}`,
    headX,
    headY,
    headZ,
    widthLeft,
    widthRight,
    heightLeft,
    heightRight,
    spacing,
    positionXLeft: 0,
    positionXRight: 0,
    positionYLeft: latitude,
    positionYRight: latitude,
    leftAngle,
    rightAngle,
    perspective: 1,
    eyeMotion: 'none',
    bodyMotion: 'none',
    mouth: 'none',
    mouthScale: 1,
  })
)

export const defaultExpression: Expression = {
  id: 'expression-neutral',
  headX: 0,
  headY: 0,
  headZ: 0,
  widthLeft: 20,
  widthRight: 20,
  heightLeft: 50,
  heightRight: 50,
  spacing: 35,
  positionXLeft: 0,
  positionXRight: 0,
  positionYLeft: -7,
  positionYRight: -7,
  leftAngle: 0,
  rightAngle: 0,
  perspective: 1,
  eyeMotion: 'none',
  bodyMotion: 'none',
  mouth: 'none',
  mouthScale: 1,
  mouthOffsetX: 0,
  mouthOffsetY: 0,
  mouthWidth: 1,
  mouthCurve: 1,
  mouthStrokeWidth: 3.2,
  effect: 'none',
}

const expressionPreset = (id: string, changes: Partial<Omit<Expression, 'id'>>): Expression => ({
  ...defaultExpression,
  id,
  ...changes,
})

const enhancedExpressions: Expression[] = [
  expressionPreset('joy', {
    headX: 5,
    headY: -5,
    headZ: -2,
    widthLeft: 30,
    widthRight: 30,
    heightLeft: 18,
    heightRight: 18,
    spacing: 38,
    positionYLeft: -2,
    positionYRight: -2,
    leftAngle: 8,
    rightAngle: -8,
    mouth: 'none',
    mouthScale: 1.15,
    eyeMotion: 'sparkle',
    effect: 'sparkles',
    bodyMotion: 'bob',
  }),
  expressionPreset('soft-smile', {
    headX: 2,
    widthLeft: 24,
    widthRight: 24,
    heightLeft: 30,
    heightRight: 30,
    mouth: 'none',
    mouthScale: 0.9,
    eyeMotion: 'microSaccades',
    bodyMotion: 'breathe',
  }),
  expressionPreset('wink', {
    headY: -10,
    headZ: -6,
    widthLeft: 26,
    widthRight: 27,
    heightLeft: 8,
    heightRight: 34,
    spacing: 38,
    leftAngle: -8,
    rightAngle: 6,
    mouth: 'none',
    eyeMotion: 'squintPulse',
    bodyMotion: 'sway',
  }),
  expressionPreset('love', {
    headX: 4,
    widthLeft: 31,
    widthRight: 31,
    heightLeft: 28,
    heightRight: 28,
    spacing: 39,
    positionYLeft: -3,
    positionYRight: -3,
    leftAngle: 10,
    rightAngle: -10,
    mouth: 'none',
    mouthScale: 1.05,
    eyeMotion: 'sparkle',
    effect: 'hearts',
    bodyColor: '#ff6f91',
    bodyMotion: 'float',
  }),
  expressionPreset('smug', {
    headY: 14,
    headZ: 8,
    widthLeft: 27,
    widthRight: 19,
    heightLeft: 19,
    heightRight: 16,
    positionYLeft: -4,
    positionYRight: -1,
    leftAngle: -8,
    rightAngle: 10,
    mouth: 'none',
    eyeMotion: 'microSaccades',
  }),
  expressionPreset('skeptical', {
    headY: -13,
    headZ: -5,
    widthLeft: 24,
    widthRight: 20,
    heightLeft: 20,
    heightRight: 13,
    positionYLeft: -3,
    positionYRight: 1,
    leftAngle: 12,
    rightAngle: -12,
    mouth: 'none',
    eyeMotion: 'squintPulse',
  }),
  expressionPreset('side-eye', {
    headY: 8,
    widthLeft: 23,
    widthRight: 23,
    heightLeft: 21,
    heightRight: 21,
    positionXLeft: 11,
    positionXRight: 11,
    positionYLeft: -3,
    positionYRight: -3,
    mouth: 'none',
    eyeMotion: 'dart',
  }),
  expressionPreset('focus', {
    headX: -4,
    widthLeft: 20,
    widthRight: 20,
    heightLeft: 22,
    heightRight: 22,
    spacing: 32,
    positionYLeft: -5,
    positionYRight: -5,
    leftAngle: -5,
    rightAngle: 5,
    eyeMotion: 'focusPulse',
    mouth: 'none',
    bodyMotion: 'breathe',
  }),
  expressionPreset('scan-left', {
    headY: -10,
    widthLeft: 23,
    widthRight: 23,
    heightLeft: 29,
    heightRight: 29,
    positionXLeft: -13,
    positionXRight: -13,
    eyeMotion: 'dart',
    mouth: 'none',
  }),
  expressionPreset('scan-right', {
    headY: 10,
    widthLeft: 23,
    widthRight: 23,
    heightLeft: 29,
    heightRight: 29,
    positionXLeft: 13,
    positionXRight: 13,
    eyeMotion: 'dart',
    mouth: 'none',
  }),
  expressionPreset('talk-a', {
    widthLeft: 24,
    widthRight: 24,
    heightLeft: 31,
    heightRight: 31,
    mouth: 'none',
    mouthScale: 0.8,
    eyeMotion: 'microSaccades',
  }),
  expressionPreset('talk-b', {
    headZ: 2,
    eyeMotion: 'focusPulse',
    widthLeft: 23,
    widthRight: 23,
    heightLeft: 28,
    heightRight: 28,
    mouth: 'none',
    mouthScale: 0.72,
  }),
  expressionPreset('talk-c', {
    headZ: -2,
    eyeMotion: 'sparkle',
    widthLeft: 25,
    widthRight: 25,
    heightLeft: 27,
    heightRight: 27,
    mouth: 'none',
    mouthScale: 0.78,
  }),
  expressionPreset('gasp', {
    headX: 7,
    widthLeft: 33,
    widthRight: 33,
    heightLeft: 47,
    heightRight: 47,
    spacing: 40,
    positionYLeft: -5,
    positionYRight: -5,
    mouth: 'none',
    mouthScale: 1.1,
    eyeMotion: 'anticipate',
    effect: 'alert',
    bodyMotion: 'bounce',
  }),
  expressionPreset('panic', {
    headX: 7,
    headZ: 5,
    widthLeft: 31,
    widthRight: 31,
    heightLeft: 48,
    heightRight: 48,
    spacing: 42,
    leftAngle: -14,
    rightAngle: 14,
    mouth: 'none',
    eyeMotion: 'shake',
    effect: 'alert',
    bodyMotion: 'shake',
  }),
  expressionPreset('sad-deep', {
    headX: -8,
    widthLeft: 22,
    widthRight: 22,
    heightLeft: 20,
    heightRight: 20,
    positionYLeft: 4,
    positionYRight: 4,
    leftAngle: -12,
    rightAngle: 12,
    mouth: 'none',
    eyeMotion: 'squintPulse',
    bodyMotion: 'slowDrift',
  }),
  expressionPreset('angry-hot', {
    headX: -5,
    widthLeft: 25,
    widthRight: 25,
    heightLeft: 15,
    heightRight: 15,
    spacing: 32,
    leftAngle: 18,
    rightAngle: -18,
    mouth: 'none',
    bodyColor: '#ef5350',
    eyeMotion: 'squintPulse',
    effect: 'errorPulse',
    bodyMotion: 'shake',
  }),
  expressionPreset('sleepy', {
    headX: -6,
    widthLeft: 24,
    widthRight: 24,
    heightLeft: 8,
    heightRight: 8,
    positionYLeft: 1,
    positionYRight: 1,
    mouth: 'none',
    eyeMotion: 'squintPulse',
    effect: 'zzz',
    bodyMotion: 'breathe',
  }),
  expressionPreset('kiss', {
    headX: 4,
    headZ: -6,
    widthLeft: 25,
    widthRight: 25,
    heightLeft: 20,
    heightRight: 20,
    leftAngle: 7,
    rightAngle: -7,
    mouth: 'none',
    mouthScale: 0.9,
    eyeMotion: 'sparkle',
    effect: 'hearts',
    bodyMotion: 'sway',
  }),
  expressionPreset('cat-cute', {
    headX: 3,
    widthLeft: 30,
    widthRight: 30,
    heightLeft: 31,
    heightRight: 31,
    spacing: 38,
    mouth: 'none',
    mouthScale: 0.8,
    eyeMotion: 'sparkle',
    bodyMotion: 'bob',
  }),
  expressionPreset('dizzy', {
    headZ: 12,
    widthLeft: 19,
    widthRight: 29,
    heightLeft: 17,
    heightRight: 34,
    leftAngle: 35,
    rightAngle: -32,
    eyeMotion: 'orbit',
    effect: 'sparkles',
    mouth: 'none',
    bodyMotion: 'sway',
  }),
  expressionPreset('notification', {
    headX: 6,
    widthLeft: 31,
    widthRight: 31,
    heightLeft: 40,
    heightRight: 40,
    spacing: 39,
    eyeMotion: 'dart',
    effect: 'alert',
    mouth: 'none',
    bodyMotion: 'bounce',
  }),
  expressionPreset('success', {
    headX: 6,
    headZ: -3,
    widthLeft: 28,
    widthRight: 28,
    heightLeft: 19,
    heightRight: 19,
    mouth: 'none',
    eyeMotion: 'sparkle',
    effect: 'successBurst',
    bodyColor: '#39c98a',
    bodyMotion: 'bounce',
  }),
  expressionPreset('error', {
    headX: -5,
    headZ: 4,
    widthLeft: 24,
    widthRight: 24,
    heightLeft: 14,
    heightRight: 14,
    leftAngle: 14,
    rightAngle: -14,
    mouth: 'none',
    eyeMotion: 'shake',
    effect: 'errorPulse',
    bodyColor: '#ff5f6d',
    bodyMotion: 'shake',
  }),
  expressionPreset('confetti', {
    headX: 8,
    headY: -4,
    widthLeft: 32,
    widthRight: 32,
    heightLeft: 22,
    heightRight: 22,
    spacing: 40,
    mouth: 'none',
    mouthScale: 1.2,
    eyeMotion: 'sparkle',
    effect: 'confetti',
    bodyMotion: 'bounce',
  }),
  expressionPreset('idle-front', {
    widthLeft: 24,
    widthRight: 24,
    heightLeft: 36,
    heightRight: 36,
    spacing: 36,
    positionYLeft: -6,
    positionYRight: -6,
    eyeMotion: 'microSaccades',
    bodyMotion: 'breathe',
  }),
  expressionPreset('idle-glance-left', {
    headY: -6,
    headZ: -1.5,
    widthLeft: 24,
    widthRight: 24,
    heightLeft: 32,
    heightRight: 32,
    spacing: 36,
    positionXLeft: -7,
    positionXRight: -7,
    positionYLeft: -6,
    positionYRight: -6,
    bodyMotion: 'breathe',
  }),
  expressionPreset('idle-glance-right', {
    headY: 6,
    headZ: 1.5,
    widthLeft: 24,
    widthRight: 24,
    heightLeft: 32,
    heightRight: 32,
    spacing: 36,
    positionXLeft: 7,
    positionXRight: 7,
    positionYLeft: -6,
    positionYRight: -6,
    bodyMotion: 'breathe',
  }),
  expressionPreset('delight', {
    headX: 5,
    headZ: -3,
    widthLeft: 31,
    widthRight: 31,
    heightLeft: 24,
    heightRight: 24,
    spacing: 40,
    leftAngle: 9,
    rightAngle: -9,
    eyeMotion: 'sparkle',
    bodyMotion: 'bounce',
    effect: 'sparkles',
  }),
  expressionPreset('eye-roll', {
    headX: -2,
    widthLeft: 24,
    widthRight: 24,
    heightLeft: 25,
    heightRight: 25,
    spacing: 37,
    positionYLeft: -12,
    positionYRight: -12,
    eyeMotion: 'orbit',
    bodyMotion: 'sway',
  }),
  expressionPreset('concern', {
    headX: -5,
    headZ: -4,
    widthLeft: 23,
    widthRight: 23,
    heightLeft: 26,
    heightRight: 19,
    spacing: 35,
    positionYLeft: 0,
    positionYRight: 2,
    leftAngle: -11,
    rightAngle: 8,
    eyeMotion: 'microSaccades',
    bodyMotion: 'slowDrift',
  }),
  expressionPreset('listening-focus', {
    headX: 2,
    headY: -5,
    headZ: -2,
    widthLeft: 25,
    widthRight: 27,
    heightLeft: 34,
    heightRight: 37,
    spacing: 37,
    positionYLeft: -6,
    positionYRight: -6,
    leftAngle: -4,
    rightAngle: 3,
    eyeMotion: 'microSaccades',
    bodyMotion: 'breathe',
  }),
  expressionPreset('puzzled', {
    headX: -2,
    headY: 9,
    headZ: 5,
    widthLeft: 27,
    widthRight: 21,
    heightLeft: 35,
    heightRight: 20,
    spacing: 37,
    positionYLeft: -6,
    positionYRight: -1,
    leftAngle: 10,
    rightAngle: -8,
    eyeMotion: 'squintPulse',
    bodyMotion: 'sway',
    effect: 'question',
  }),
  expressionPreset('determined', {
    headX: -4,
    widthLeft: 27,
    widthRight: 27,
    heightLeft: 17,
    heightRight: 17,
    spacing: 31,
    leftAngle: 15,
    rightAngle: -15,
    eyeMotion: 'focusPulse',
    bodyMotion: 'breathe',
  }),
  expressionPreset('anticipation', {
    headX: 4,
    widthLeft: 29,
    widthRight: 29,
    heightLeft: 41,
    heightRight: 41,
    spacing: 40,
    positionYLeft: -5,
    positionYRight: -5,
    eyeMotion: 'anticipate',
    bodyMotion: 'bob',
  }),
  expressionPreset('cheer', {
    headX: 8,
    headZ: -5,
    widthLeft: 32,
    widthRight: 32,
    heightLeft: 18,
    heightRight: 18,
    spacing: 41,
    leftAngle: 12,
    rightAngle: -12,
    eyeMotion: 'sparkle',
    bodyMotion: 'bounce',
    effect: 'confetti',
  }),
  expressionPreset('intro-neby-closed', {
    headX: -10,
    headY: -13,
    headZ: -7,
    widthLeft: 27,
    widthRight: 27,
    heightLeft: 6,
    heightRight: 6,
    spacing: 36,
    positionYLeft: 4,
    positionYRight: 4,
    bodyMotion: 'slowDrift',
    effect: 'introGlow',
  }),
  expressionPreset('intro-neby-peek', {
    headX: -4,
    headY: 9,
    headZ: 4,
    widthLeft: 27,
    widthRight: 27,
    heightLeft: 19,
    heightRight: 31,
    spacing: 38,
    positionXLeft: 5,
    positionXRight: 5,
    leftAngle: -7,
    rightAngle: 6,
    eyeMotion: 'anticipate',
    effect: 'introGlow',
  }),
  expressionPreset('intro-neby-focus', {
    headX: 1,
    widthLeft: 29,
    widthRight: 29,
    heightLeft: 39,
    heightRight: 39,
    spacing: 40,
    positionYLeft: -7,
    positionYRight: -7,
    eyeMotion: 'focusPulse',
    bodyMotion: 'breathe',
    effect: 'introGlow',
  }),
  expressionPreset('intro-neby-signature', {
    headX: 5,
    headZ: -2,
    widthLeft: 31,
    widthRight: 31,
    heightLeft: 23,
    heightRight: 23,
    spacing: 42,
    leftAngle: 8,
    rightAngle: -8,
    eyeMotion: 'sparkle',
    bodyMotion: 'float',
    effect: 'sparkles',
  }),
  expressionPreset('intro-pop', {
    headX: 7,
    widthLeft: 34,
    widthRight: 34,
    heightLeft: 43,
    heightRight: 43,
    spacing: 42,
    eyeMotion: 'anticipate',
    bodyMotion: 'bounce',
    effect: 'successBurst',
  }),
  expressionPreset('intro-scan', {
    headY: -7,
    widthLeft: 25,
    widthRight: 25,
    heightLeft: 31,
    heightRight: 31,
    spacing: 38,
    eyeMotion: 'dart',
    bodyMotion: 'slowDrift',
    effect: 'introGlow',
  }),
]

export const initialExpressions: Expression[] = [...calibratedExpressions, ...enhancedExpressions]

export const expressionDisplayNames: Record<string, string> = {
  joy: 'Joy',
  'soft-smile': 'Soft smile',
  wink: 'Wink',
  love: 'Love',
  smug: 'Smug',
  skeptical: 'Skeptical',
  'side-eye': 'Side eye',
  focus: 'Focus',
  'scan-left': 'Scan left',
  'scan-right': 'Scan right',
  'talk-a': 'Talk A',
  'talk-b': 'Talk O',
  'talk-c': 'Talk smile',
  gasp: 'Gasp',
  panic: 'Panic',
  'sad-deep': 'Deep sad',
  'angry-hot': 'Angry',
  sleepy: 'Sleepy',
  kiss: 'Kiss',
  'cat-cute': 'Cat cute',
  dizzy: 'Dizzy',
  notification: 'Notification',
  success: 'Success',
  error: 'Error',
  confetti: 'Confetti',
  'idle-front': 'Idle front',
  'idle-glance-left': 'Idle glance left',
  'idle-glance-right': 'Idle glance right',
  delight: 'Delight',
  'eye-roll': 'Eye roll',
  concern: 'Concern',
  'listening-focus': 'Listening focus',
  puzzled: 'Puzzled',
  determined: 'Determined',
  anticipation: 'Anticipation',
  cheer: 'Cheer',
  'intro-neby-closed': 'Neby intro · hush',
  'intro-neby-peek': 'Neby intro · peek',
  'intro-neby-focus': 'Neby intro · focus',
  'intro-neby-signature': 'Neby intro · signature',
  'intro-pop': 'Intro pop',
  'intro-scan': 'Intro scan',
}

export const getExpressionDisplayName = (expression: Expression, index: number) =>
  expressionDisplayNames[expression.id] ?? String(index).padStart(2, '0')

export const stateGroups = {
  Intros: ['intro-neby', 'intro-cinematic', 'intro-pop', 'intro-scan'],
  'Cycle de vie': [
    'sleeping',
    'waking',
    'idle',
    'listening',
    'thinking',
    'searching',
    'working',
    'speaking',
    'presenting',
    'scanning',
  ],
  Réactions: [
    'excited',
    'surprised',
    'suspicious',
    'angry',
    'drowsy',
    'happy',
    'curious',
    'confused',
    'bored',
    'proud',
    'shy',
    'sad',
    'laughing',
    'scared',
    'playful',
    'celebrate',
    'greeting',
    'agree',
    'disagree',
    'wink',
    'love',
    'success',
    'error',
    'notification',
    'dizzy',
    'dance',
  ],
} as const

const expressionIndex = (id: string) => {
  const index = initialExpressions.findIndex(expression => expression.id === id)
  return index >= 0 ? index : 0
}
const expressionPool = (...ids: string[]) => ids.map(expressionIndex)

export const statePools: Record<string, number[]> = {
  'intro-neby': expressionPool(
    'intro-neby-closed',
    'intro-neby-peek',
    'intro-neby-focus',
    'intro-neby-signature',
    'idle-front'
  ),
  'intro-cinematic': expressionPool('sleepy', 'anticipation', 'focus', 'delight', 'idle-front'),
  'intro-pop': expressionPool('sleepy', 'intro-pop', 'cheer', 'soft-smile'),
  'intro-scan': expressionPool('scan-left', 'scan-right', 'intro-scan', 'determined', 'idle-front'),
  sleeping: expressionPool('sleepy', 'sleepy', 'sleepy'),
  waking: expressionPool('sleepy', 'anticipation', 'idle-front'),
  idle: expressionPool('idle-front', 'idle-glance-left', 'idle-front', 'idle-glance-right'),
  listening: expressionPool('idle-front', 'listening-focus', 'idle-front'),
  thinking: expressionPool('skeptical', 'eye-roll', 'side-eye', 'focus'),
  searching: expressionPool('scan-left', 'focus', 'scan-right'),
  working: expressionPool('focus', 'scan-left', 'determined', 'scan-right'),
  speaking: expressionPool('talk-a', 'talk-b', 'talk-c', 'soft-smile'),
  presenting: expressionPool('focus', 'soft-smile', 'anticipation', 'soft-smile'),
  scanning: expressionPool('scan-left', 'intro-scan', 'scan-right'),
  excited: expressionPool('anticipation', 'delight', 'cheer', 'joy'),
  surprised: expressionPool('anticipation', 'gasp', 'delight'),
  suspicious: expressionPool('skeptical', 'side-eye', 'determined'),
  angry: expressionPool('determined', 'angry-hot', 'skeptical'),
  drowsy: expressionPool('sleepy', 'concern', 'sleepy'),
  happy: expressionPool('soft-smile', 'delight', 'joy'),
  curious: expressionPool('anticipation', 'side-eye', 'focus'),
  confused: expressionPool('skeptical', 'puzzled', 'eye-roll'),
  bored: expressionPool('sleepy', 'side-eye', 'eye-roll'),
  proud: expressionPool('smug', 'soft-smile', 'determined'),
  shy: expressionPool('soft-smile', 'kiss', 'concern'),
  sad: expressionPool('concern', 'sad-deep', 'concern'),
  laughing: expressionPool('joy', 'delight', 'joy'),
  scared: expressionPool('anticipation', 'panic', 'gasp'),
  playful: expressionPool('wink', 'cat-cute', 'side-eye', 'joy'),
  celebrate: expressionPool('cheer', 'confetti', 'success', 'joy'),
  greeting: expressionPool('anticipation', 'wink', 'soft-smile', 'delight'),
  agree: expressionPool('soft-smile', 'success', 'idle-front'),
  disagree: expressionPool('skeptical', 'error', 'side-eye'),
  wink: expressionPool('idle-front', 'wink', 'soft-smile'),
  love: expressionPool('anticipation', 'love', 'soft-smile'),
  success: expressionPool('anticipation', 'success', 'confetti', 'soft-smile'),
  error: expressionPool('focus', 'error', 'concern'),
  notification: expressionPool('idle-front', 'notification', 'focus'),
  dizzy: expressionPool('dizzy', 'eye-roll', 'dizzy'),
  dance: expressionPool('cheer', 'wink', 'love', 'joy'),
}

export const stateDisplayNames: Record<string, string> = {
  'intro-neby': 'Neby — Cinematic Reveal',
  'intro-cinematic': 'Cinematic Character Reveal',
  'intro-pop': 'Playful Pop Intro',
  'intro-scan': 'Tech Scan Intro',
  celebrate: 'Celebrate + Confetti',
  notification: 'Notification Attention',
}

export type StatePlaybackConfig = {
  expressionIntervalMs: number
  blink: {
    initialDelayMs: number
    minIntervalMs: number
    maxIntervalMs: number
    durationMs: number
  }
}

const blinkProfiles = {
  natural: {
    initialDelayMs: 2600,
    minIntervalMs: 3400,
    maxIntervalMs: 6200,
    durationMs: 280,
  },
  calm: {
    initialDelayMs: 4800,
    minIntervalMs: 6500,
    maxIntervalMs: 9500,
    durationMs: 420,
  },
  attentive: {
    initialDelayMs: 3200,
    minIntervalMs: 4800,
    maxIntervalMs: 7200,
    durationMs: 240,
  },
  active: {
    initialDelayMs: 2100,
    minIntervalMs: 2800,
    maxIntervalMs: 5000,
    durationMs: 260,
  },
  reactive: {
    initialDelayMs: 1200,
    minIntervalMs: 1800,
    maxIntervalMs: 3600,
    durationMs: 220,
  },
} as const

const introStates = new Set(['intro-neby', 'intro-cinematic', 'intro-pop', 'intro-scan'])
const calmStates = new Set(['sleeping', 'drowsy', 'bored', 'sad'])
const attentiveStates = new Set(['listening', 'thinking', 'working', 'searching', 'scanning'])
const fastStates = new Set([
  'speaking',
  'excited',
  'surprised',
  'laughing',
  'scared',
  'celebrate',
  'greeting',
  'agree',
  'disagree',
  'wink',
  'love',
  'success',
  'error',
  'notification',
  'dizzy',
  'dance',
])

export const getStatePlaybackConfig = (name: string): StatePlaybackConfig => {
  const blink =
    name === 'idle'
      ? blinkProfiles.natural
      : introStates.has(name)
        ? blinkProfiles.attentive
        : calmStates.has(name)
          ? blinkProfiles.calm
          : attentiveStates.has(name)
            ? blinkProfiles.attentive
            : fastStates.has(name)
              ? blinkProfiles.reactive
              : blinkProfiles.active
  return {
    expressionIntervalMs:
      name === 'idle'
        ? 1150
        : introStates.has(name)
          ? 560
          : calmStates.has(name)
            ? 1050
            : attentiveStates.has(name)
              ? 720
              : fastStates.has(name)
                ? 420
                : 620,
    blink: { ...blink },
  }
}


export const stateNotes: Record<string, string> = {
  'intro-neby': 'Intro cinématique Neby : silence, regard qui s’ouvre, verrouillage caméra et signature lumineuse.',
  'intro-cinematic': 'Révélation courte et premium, conçue pour présenter un personnage dans une app ou une vidéo.',
  'intro-pop': 'Entrée vive et ludique avec anticipation, pop visuel et regard souriant.',
  'intro-scan': 'Intro technologique : balayage du regard, focus puis pose de signature.',
  sleeping: 'Yeux presque fermés, respiration lente et expression de sommeil.',
  waking: 'Animation courte de réveil avant retour vers une expression neutre.',
  idle: 'Regard frontal au repos, puis brèves œillades latérales avec respiration légère.',
  listening: 'Regard frontal attentif, légère inclinaison et micro-ajustements sans dépendre d’une bouche.',
  thinking: 'Regard haut et latéral, expressions asymétriques et changements fréquents.',
  searching: 'Balayage rapide et changements très fréquents.',
  working: 'Rythme régulier et expressions concentrées.',
  excited: 'Grandes expressions et transitions rapides.',
  curious: 'Inclinaisons et forte asymétrie.',
  speaking: 'Cycle de jeu oculaire A/B/C et micro-saccades pour parler visuellement même bouche désactivée.',
  presenting: 'Gestuelle calme, regard engagé et sourire léger.',
  scanning: 'Balayage latéral du regard pour les agents en recherche.',
  greeting: 'Accueil chaleureux avec clin d’œil et rebond subtil.',
  agree: 'Réaction positive courte pour confirmer une action.',
  disagree: 'Réaction négative lisible sans agressivité excessive.',
  success: 'Réussite courte avec anticipation, burst visuel et retour propre vers le regard frontal.',
  error: 'Signal d’erreur expressif avec tremblement bref.',
  notification: 'Accroche visuelle rapide : snap du regard, alerte, puis recentrage sans pause morte.',
  dance: 'Boucle ludique plus rythmée, sans longs temps morts, pilotée surtout par les yeux.',
  celebrate: 'Célébration avec vrais confettis procéduraux, yeux pétillants et rebond bref.',
}
